controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: velocity_controllers/JointGroupVelocityController

# Gripper
arm_controller:
  ros__parameters:
    joints:
      - slider_joint1
      - slider_joint2
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity